# Generated by Django 2.0.1 on 2018-09-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('core', '0002_auto_20180913_1115'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrecruiter',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyaddress', to='core.Address'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='companyrecruiter',
            unique_together={('company', 'recruiter')},
        ),
    ]
