# Generated by Django 2.0.1 on 2018-09-21 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creator', models.UUIDField(default=uuid.uuid4)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modifier', models.UUIDField(default=uuid.uuid4)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SHORTLISTED', 'SHORTLISTED'), ('JOB OFFERED', 'JOB OFFERED'), ('RECRUITED', 'RECRUITED'), ('OFFER_REJECTED', 'OFFER_REJECTED'), ('CANDIDATE_REJECTED', 'CANDIDATE_REJECTED')], default='APPLIED', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'INITIAL'), ('WAITING FOR APPROVAL', 'WAITING FOR APPROVAL'), ('POSTED', 'POSTED'), ('HOLD', 'HOLD'), ('EXPIRED', 'EXPIRED')], max_length=30),
        ),
    ]
