# Generated by Django 2.0.1 on 2018-09-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_auto_20180921_1221'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobPosting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_posting.JobPosting'),
        ),
    ]
